<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3NtpvG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3NtpvG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX3NtpvG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX3NtpvG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX3NtpvG\App_KernelDevDebugContainer([
    'container.build_hash' => 'X3NtpvG',
    'container.build_id' => 'cf383c18',
    'container.build_time' => 1683881822,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3NtpvG');
