<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsrJjrk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsrJjrk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIsrJjrk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIsrJjrk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIsrJjrk\App_KernelDevDebugContainer([
    'container.build_hash' => 'IsrJjrk',
    'container.build_id' => '36c21349',
    'container.build_time' => 1683918381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsrJjrk');
