<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyam66h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyam66h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyam66h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyam66h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyam66h\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xyam66h',
    'container.build_id' => '694d5aad',
    'container.build_time' => 1683706574,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyam66h');
